site_name: 'Moth: A Grace on top of SOMns'
# site_url:
site_description: Moth Project documentation
site_author: Moth contributors

pages:
  - 'Moth: A Grace on top of SOMns': index.md
  - For Users:
      - Basic User Setup: basic-setup.md
      - Moth Launcher: launcher.md
  - For Developers:
      - Development Setup: dev-setup.md
      - Repository and Code Layout: repo-layout.md
      - Development Infrastructure: infrastructure.md
      - Release Checklist: release-checklist.md
      - Extensions: extensions.md
  - License:    LICENSE.md
  - README:     README.md
  - Change Log: CHANGELOG.md
  - Authors:    AUTHORS.md

markdown_extensions:
  - toc:
      permalink: True
